markdown: redcarpet 
permalink: /:year/:month/:title/
url: http://pineal.me
author: Hesen Zhang
highligher: pygments
#paginate: 24
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]