markdown: rdiscount
permalink: /:year/:month/:title/
url: http://pineal.github.com
author: Hesen Zhang
pygments: true
paginate: 24
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]