markdown: Kramdown
permalink: /:year/:month/:title/
url: http://pineal.me
author: Hesen Zhang
#paginate: 24
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
kramdown:
  default_lang: c++
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  enable_coderay: false